### ISSUE TITLE
Align data science notebooks with machine learning ones. 

### ISSUE THREAD

**Issue by HikkaV** [HikkaV/DS-ML-Courses#3]
Please, try to align the format of data science notebooks with machine learning ones.
1) Every notebook starts with the short description of assignment.
2) Everything is explained, thus no one is frustrated.
3) Use html tagging instead of rest, etc. (as html tags are more flexible)
4) The notebook is divided into parts (part 1 : data loading, part 2: processing, and so on)
5) Use more we than I, you, when describing notebooks.
6) At the end of the notebook, the one should sum up, what was achieved in it, conclude main ideas.

**Comment by Vital95** [comment]
Updated
